global using AutoMapper;
global using Catalog.Application.Common.Response;
global using Catalog.BusinessLogic.Contracts.Services;
global using Catalog.BusinessLogic.Models;
global using Catalog.BusinessLogic.Services;
global using Catalog.BusinessLogic.Services.Base;
global using Catalog.Domain.Entities;
global using Catalog.Persistence;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Caching.Distributed;
global using DistributedCacheExtensions = Catalog.Application.Extensions.DistributedCacheExtensions;
global using Catalog.Application.Common.Response.Contracts;
global using Catalog.Application.Common.Response.CustomResponses.Base;
global using Catalog.Application.Constants;
global using Catalog.Domain.Entities.Base;
global using Microsoft.Extensions.DependencyInjection;